services:
  postgres:
    container_name: from-poland-db
    image: postgres:11-alpine
    command: postgres -c 'max_connections=200'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-frompoland123}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    volumes:
      - ./init/init-database.sql:/docker-entrypoint-initdb.d/init-database.sql
      - ./.volumes/postgres/:/var/lib/postgresql/data/
    networks:
      - default
